$(document).ready(function(){
    $("#JAVA8").click(function(){
        window.location.href="https://zq99299.github.io/java-tutorial/";
    });
    $("#google").click(function(){
        window.location.href="http://www.google.com";
    });
	  $("#bridge").click(function(){
        window.location.href="https://bridges.torproject.org/";
    });
	  $("#JAVA_study").click(function(){
        window.location.href="https://hollischuang.github.io/toBeTopJavaer/#/basics/java-basic/basic-data-types";
    });
	  $("#Webpro").click(function(){
        window.location.href="https://chinese.freecodecamp.org/learn/";
    });
	  $("#Font").click(function(){
        window.location.href="https://fontawesome.dashgame.com/";
    });
    $("#translate").click(function(){
        window.location.href="https://translate.google.cn";
    });
    $("#leetcode").click(function(){
        window.location.href="https://leetcode-cn.com/";
    });
    $("#csdn").click(function(){
        window.location.href="https://www.csdn.net/";
    });
    $("#TyingCode").click(function(){
        window.location.href="https://kaiyiwing.gitee.io/qwerty-learner/";
    });
    $("#LinuxM").click(function(){
        window.location.href="https://wangchujiang.com/linux-command/";
    });
    $("#github").click(function(){
        window.location.href="https://github.com";
    });
    $("#bilibili").click(function(){
        window.location.href="https://www.bilibili.com";
    });
    $("#cnblog").click(function(){
        window.location.href="https://www.cnblogs.com/";
    });
    $("#Web_API").click(function(){
        window.location.href="https://developer.mozilla.org/zh-CN/docs/Web/API";
    });
    $("#SiWei").click(function(){
        window.location.href="https://www.zxgj.cn/g/siweidaotu";
    });
	
	$("#gitee").click(function(){
	    window.location.href="https://gitee.com/";
	});
	$("#CodeTransform").click(function(){
	    window.location.href="https://www.zxgj.cn/g/unicode";
	});
	$("#Web_Miansi").click(function(){
	    window.location.href="https://fe.padding.me/#/";
	});
	$("#JavaScript2").click(function(){
	    window.location.href="https://tsejx.github.io/javascript-guidebook/";
	});
	$("#LoGoPond").click(function(){
	    window.location.href="https://logopond.com/";
	});
	$("#WaBI").click(function(){
	    window.location.href="http://www.wabi.com/";
	});
	$("#Qukuaicaijing").click(function(){
	    window.location.href="https://www.jinse.com/";
	});
	$("#Tool1").click(function(){
	    window.location.href="https://web.woobx.cn/";
	});
	$("#GitChat").click(function(){
	    window.location.href="https://gitbook.cn/";
	});
	$("#Iconic1").click(function(){
	    window.location.href="https://www.iconfont.cn/";
	});
	$("#MarkDown").click(function(){
	    window.location.href="https://markdown.com.cn/cheat-sheet.html";
	});
	$("#Suanfa").click(function(){
	    window.location.href="https://github.com/labuladong/fucking-algorithm";
	});
	$("#JSGuid").click(function(){
	    window.location.href="http://www.htmldrive.net/";
	});
	$("#Vue").click(function(){
	    window.location.href="http://caibaojian.com/vue-design/";
	});
	$("#Web_list").click(function(){
	    window.location.href="https://cheatsheets.devtool.tech/";
	});
	$("#JavaScript3").click(function(){
	    window.location.href="https://www.toolnb.com/toolslist/14.html";
	});
	$("#Shujujiego").click(function(){
	    window.location.href="https://www.kancloud.cn/alex_wsc/dataalg";
	});
	$("#CssIconic").click(function(){
	    window.location.href="https://css.gg/";
	});
	$("#tool2").click(function(){
	    window.location.href="https://tiomg.org/";
	});
	$("#LoGOzhizuo").click(function(){
	    window.location.href="http://www.uugai.com/";
	});
	$("#QukuaiJava").click(function(){
	    window.location.href="https://www.zhihu.com/pub/reader/119976643";
	});
	$("#ErweiMa").click(function(){
	    window.location.href="https://mh.cli.im/";
	});
	$("#GO1").click(function(){
	    window.location.href="https://studygolang.gitbook.io/learn-go-with-tests/";
	});
	$("#HTML5").click(function(){
	    window.location.href="https://www.html5tricks.com/";
	});
	$("#OSCHINA").click(function(){
	    window.location.href="https://www.oschina.net/";
	});
	$("#JAVApoint").click(function(){
	    window.location.href="https://www.javatpoint.com/";
	});
	$("#Turtail").click(function(){
	    window.location.href="https://www.tutorialspoint.com/index.htm";
	});
	$("#Fanqiang").click(function(){
	    window.location.href="https://10beasts.net/recommend/";
	});
	$("#xuexiziyuan").click(function(){
	    window.location.href="https://github.com/liyupi/free-programming-resources";
	});
	$("#bianchengbiji").click(function(){
	    window.location.href="http://www.cyc2018.xyz/#%E7%AE%97%E6%B3%95";
	});
	$("#xuexiluxian").click(function(){
	    window.location.href="https://how2j.cn/frontroute";
	});
	$("#Git").click(function(){
	    window.location.href="https://backlog.com/git-tutorial/cn/";
	});
	$("#Suanfaxuexi").click(function(){
	    window.location.href="https://lucifer.ren/blog/";
	});
	$("#Web_list2").click(function(){
	    window.location.href="http://code.ciaoca.com/";
	});
	$("#CSsjiaocheng").click(function(){
	    window.location.href="https://zh.learnlayout.com/no-layout.html";
	});
	$("#JaVaNode").click(function(){
	    window.location.href="https://zq99299.github.io/java-tutorial/";
	});
	$("#Tying1").click(function(){
	    window.location.href="https://www.typingclub.com/";
	});
	$("#Tying2").click(function(){
	    window.location.href="https://www.keybr.com/";
	});
	$("#Soft").click(function(){
	    window.location.href="https://www.rjsos.com/win";
	});
	$("#Go_Web").click(function(){
	    window.location.href="https://geektutu.com/post/gee.html";
	});
	$("#Cjiajia").click(function(){
	    window.location.href="https://zh.cppreference.com/w/%E9%A6%96%E9%A1%B5";
	});
	$("#yibai").click(function(){
	    window.location.href="https://www.yiibai.com/?app=all";
	});
	$("#yuanma").click(function(){
	    window.location.href="http://www.zuidaima.com/";
	});
	$("#zaixian1").click(function(){
	    window.location.href="https://www.tutorialspoint.com/codingground.htm";
	});
	$("#zaixian2").click(function(){
	    window.location.href="http://www.dooccn.com/";
	});
	$("#zaixian3").click(function(){
	    window.location.href="https://learn.freecodecamp.one/";
	});
	$("#BTC").click(function(){
	    window.location.href="https://www.feixiaohao.cc/";
	});
	$("#lvye").click(function(){
	    window.location.href="http://www.lvyestudy.com/";
	});
	$("#VPN").click(function(){
	    window.location.href="https://www.nangua110.com/";
	});
	$("#Jiaoben").click(function(){
	    window.location.href="https://greasyfork.org/zh-CN/scripts";
	});
	$("#youdao").click(function(){
	    window.location.href="http://halihali2.com/";
	});
	$("#JavaScript1").click(function(){
	    window.location.href="https://zh.javascript.info/";
	});
	$("#Web_list1").click(function(){
	    window.location.href="http://shouce.jb51.net/";
	});
})
